### ISSUE TITLE
Question - Why store & update does not use factories ?

### ISSUE THREAD

**Issue by YannikFirre** [fidum/laravel-blueprint-pestphp-addon#27]
Hello,

I have a question about test generation for the store and update methods.

Why the data sent in the request does not use the factory? 

Currently:
![image](https://user-images.githubusercontent.com/3316758/129481004-6c2436f9-bc55-4de2-8751-8a26f26e653d.png)

Changed by : 
![image](https://user-images.githubusercontent.com/3316758/129480994-f8339d6b-2bc0-482b-91ad-fecc263bd218.png)

Thank you in advance for your reply

**Comment by dmason30** [comment]
Hi, thanks for the question. 

It is a fair point, however, this package tries to keep feature parity with the Blueprint packages PHPUnit tests. Which are currently using faker too:

https://github.com/laravel-shift/blueprint/blob/67cfc6b01c50545a5f050fa4f88633993e759f21/tests/fixtures/tests/reference-cache-laravel8.php#L33

One reason why not do to this is if the factory generates fields that you would not want in the request... timestamps etc.

If you could raise the issue on the Blueprint repository and see if they think its a good idea to change and I keep track of their releases and will follow suit if the change is made. 

I will close this for now, feel free to open another issue to remind me if Blueprint end up implementing it and I haven't made the changes yet.
