### ISSUE TITLE
add support for v2 of laravel-test-assertions package

### ISSUE THREAD

**Issue by bnomei** [fidum/laravel-blueprint-pestphp-addon#30]
https://github.com/jasonmccreary/laravel-test-assertions

**Comment by dmason30** [comment]
Please open an issue with more detail on your problem. Closing this.

**Comment by dmason30** [comment]
This has already been done in v2.0.0 of this package. Please upgrade.

**Comment by bnomei** [comment]
really?
https://github.com/fidum/laravel-blueprint-pestphp-addon/blob/47caf5afb0f2e08718ae0a9c7086a7a4a8548183/composer.json#L24

**Comment by dmason30** [comment]
Apologies tagged 2.0.1 https://github.com/fidum/laravel-blueprint-pestphp-addon/releases/tag/2.0.1
